--insert into answer (question_id, label, status_code_id) values 
--insert into question (label, status_code_id) values 
--insert into survey_question (survey_id, question_id, status_code_id) values 
--select email, user_id from "user" where email != ''
--insert into "user" (email, firstname, lastname, custom_data, status_code_id) values
--insert into user_survey (user_id, survey_id, collector_id, date_start, date_end, status_code_id, ip_address) values
--insert into temp_entry values
