select * from user_survey_answer order by 1 desc limit 1
select * from user_survey_answer_comment order by 1 desc limit 1
select * from survey order by 1 desc limit 1
select * from survey_question order by 1 desc limit 1
select * from question order by 1 desc limit 1
select * from survey order by 1 desc limit 1
select * from "user" order by 1 desc limit 1
select * from answer order by 1 desc limit 1
select * from temp_entry order by 1 desc limit 1